name: "Install dependencies"
description: "Prepare repository and install all dependencies with bun"

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: bun ci
