import type { GameDefinition } from "./types";

function img(file: string) {
	return { file: `sprites/${file}`, version: 1 };
}
function map(file: string) {
	return { file: `maps/${file}`, version: 1 };
}
function snd(file: string) {
	return { file: `sounds/${file}`, version: 1 };
}

export const games: GameDefinition[] = [
	{
		id: "bird",
		name: "Flappy Bird",
		description: "Dodge the pipes! A classic side-scrolling arcade game.",
		category: "arcade",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot", "update.loot", "audio.loot", "collisions.loot", "particles.loot"],
		resources: {
			images: [
				img("bird1.png"),
				img("bird2.png"),
				img("cloud0.png"),
				img("cloud1.png"),
				img("cloud2.png"),
				img("icon.png"),
				img("pipe.png"),
				img("pipebottom.png"),
				img("pipetop.png"),
				img("poster.png"),
				img("sea.png"),
				img("bar.png"),
			],
			maps: [map("map1.json"), map("sea.json")],
		},
		color: "#39ff14",
	},
	{
		id: "blockparty",
		name: "Block Party",
		description: "Fill rows and columns to clear blocks. Puzzle fun!",
		category: "puzzle",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot", "board.loot", "pieces.loot", "input.loot", "audio.loot"],
		color: "#ff00ff",
	},
	{
		id: "fish",
		name: "Fish Adventure",
		description: "Dive deep and catch fish while dodging sea creatures.",
		category: "adventure",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: [
			"main.loot",
			"fish.loot",
			"animals.loot",
			"crabs.loot",
			"draw.loot",
			"physics.loot",
			"levels.loot",
			"keyboard.loot",
			"gamepad.loot",
			"gesture.loot",
			"audio.loot",
			"music.loot",
			"message.loot",
		],
		resources: {
			images: [
				img("arrowup.png"),
				img("crab.png"),
				img("doigt.png"),
				img("door0.png"),
				img("door1.png"),
				img("fish.png"),
				img("fish1.png"),
				img("fish2.png"),
				img("fishscore.png"),
				img("huit.png"),
				img("icon.png"),
				img("mast.png"),
				img("octopus1.png"),
				img("octopus2.png"),
				img("piranha1.png"),
				img("piranha2.png"),
				img("piranhaback0.png"),
				img("piranhaback1.png"),
				img("piranhafront0.png"),
				img("piranhafront1.png"),
				img("poster.png"),
				img("rock0.png"),
				img("rock1.png"),
				img("rock2.png"),
				img("sailor.png"),
				img("sandbottom0.png"),
				img("sandbottom1.png"),
				img("sandbottomright0.png"),
				img("sandbottomright1.png"),
				img("sandfull.png"),
				img("sandleft0.png"),
				img("sandleft1.png"),
				img("sandleftbottom0.png"),
				img("sandleftbottom1.png"),
				img("sandright0.png"),
				img("sandright1.png"),
				img("sandtop0.png"),
				img("sandtop1.png"),
				img("sandtopleft0.png"),
				img("sandtopleft1.png"),
				img("sandtopright0.png"),
				img("sandtopright1.png"),
				img("sea.png"),
				img("shark1.png"),
				img("shark2.png"),
				img("ship.png"),
				img("ship2.png"),
				img("shiptop.png"),
				img("wall0.png"),
				img("wall1.png"),
				img("wallsand.png"),
				img("walltile.png"),
				img("wave0.png"),
				img("wave1.png"),
				img("wave2.png"),
				img("wave3.png"),
				img("wave4.png"),
			],
			maps: [
				map("map1.json"),
				map("map2.json"),
				map("map3.json"),
				map("map4.json"),
				map("map5.json"),
				map("map6.json"),
				map("map7.json"),
				map("map8.json"),
			],
		},
		color: "#00bfff",
	},
	{
		id: "scenes",
		name: "Scene Routing",
		description: "Multi-scene demo with navigation and route params.",
		category: "demo",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot", "scenes/home.loot", "scenes/battle.loot", "scenes/player.loot"],
		color: "#ffb300",
	},
	{
		id: "skate",
		name: "Skate Runner",
		description: "Shred the streets and dodge obstacles at high speed!",
		category: "arcade",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot"],
		resources: {
			images: [
				img("blade.png"),
				img("hero.png"),
				img("hero2.png"),
				img("heroblink.png"),
				img("icon.png"),
				img("wall.png"),
			],
			maps: [
				map("map1.json"),
				map("map2.json"),
				map("map3.json"),
				map("map4.json"),
				map("map5.json"),
				map("map6.json"),
				map("map7.json"),
				map("map8.json"),
			],
		},
		color: "#ff6b35",
	},
	{
		id: "sprite-jump",
		name: "Sprite Jump",
		description: "Jump from platform to platform and climb to the sky!",
		category: "arcade",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: [
			"main.loot",
			"mainfunctions.loot",
			"platfrom.loot",
			"platfromfunctions.loot",
			"player.loot",
			"playerfunctions.loot",
		],
		resources: {
			images: [
				img("bg.png"),
				img("icon.png"),
				img("playerleft.png"),
				img("playerright.png"),
				img("poster.png"),
				img("platforms/normalplatform.png"),
				img("platforms/movingplatform.png"),
				img("platforms/woodplatform.png"),
				img("platforms/jumpplatformleft.png"),
				img("platforms/jumpplatformmiddle.png"),
				img("platforms/jumpplatformright.png"),
			],
			sounds: [snd("jumpsound.wav"), snd("gameoversound.wav"), snd("woodbreak.wav")],
		},
		color: "#e040fb",
	},
	{
		id: "hello",
		name: "Hello World",
		description: "Animated wave text - the classic first program.",
		category: "demo",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot"],
		color: "#00fff5",
	},
	{
		id: "draw",
		name: "Draw",
		description: "Freeform drawing canvas powered by LootiScript.",
		category: "demo",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot"],
		color: "#76ff03",
	},
	{
		id: "dino-runner",
		name: "Dino Runner",
		description: "Run, jump, and survive in this endless runner!",
		category: "arcade",
		orientation: "portrait",
		width: 1080,
		height: 1920,
		sources: ["main.loot"],
		resources: {
			images: [img("hero.png"), img("wall.png"), img("blade.png"), img("icon.png")],
		},
		color: "#ff1744",
	},
];

export function getGame(id: string): GameDefinition | undefined {
	return games.find((g) => g.id === id);
}
