/**
 * Contract Wrapper Generator Adapter
 *
 * Generates LootiScript wrapper code from contract ABI
 */

import type { ABIItem, ContractABI } from "../../../core/types";

/**
 * Generate LootiScript wrapper from ABI
 */
export function generateLootiScriptWrapper(abi: ContractABI, contractAddress: string, contractName: string): string {
	const functions = abi.filter((item: ABIItem) => item.type === "function");
	const events = abi.filter((item: ABIItem) => item.type === "event");

	// Sanitize contract name for safe use in code (only alphanumeric and underscore)
	const safeContractName = contractName.replace(/[^a-zA-Z0-9_]/g, "_");
	if (!/^[a-zA-Z_]/.test(safeContractName)) {
		throw new Error(`Invalid contract name: must start with letter or underscore`);
	}

	// Escape contract address for safe use in string
	const safeAddress = JSON.stringify(contractAddress);

	let code = `// Auto-generated contract wrapper for ${safeContractName}
// Address: ${contractAddress}
// Generated by: l8b contract import

local ${safeContractName} = object
  address = ${safeAddress},
  abi = ${JSON.stringify(abi, null, 2)}
end

// Read functions (view/pure - no transaction)
`;

	// Generate read functions
	for (const func of functions.filter((f: ABIItem) => f.stateMutability === "view" || f.stateMutability === "pure")) {
		// Sanitize function name
		const safeFuncName = func.name?.replace(/[^a-zA-Z0-9_]/g, "_") ?? "";
		if (!safeFuncName || !/^[a-zA-Z_]/.test(safeFuncName)) {
			continue; // Skip invalid function names
		}
		const params = (func.inputs ?? [])
			.map((input, i: number) => {
				const paramName = input.name ? input.name.replace(/[^a-zA-Z0-9_]/g, "_") : `arg${i}`;
				return /^[a-zA-Z_]/.test(paramName) ? paramName : `arg${i}`;
			})
			.join(", ");

		// Escape function name for safe use in string
		const safeFuncNameStr = JSON.stringify(func.name);

		code += `
async function ${safeContractName}.${safeFuncName}(${params})
  return await evm.read(
    ${safeContractName}.address,
    ${safeContractName}.abi,
    ${safeFuncNameStr},
    {${(func.inputs ?? []).map((_: unknown, i: number) => `arg${i + 1}`).join(", ")}}
  )
end
`;
	}

	code += `
// Write functions (state-changing - sends transaction)
`;

	// Generate write functions
	for (const func of functions.filter((f: ABIItem) => f.stateMutability !== "view" && f.stateMutability !== "pure")) {
		// Sanitize function name
		const safeFuncName = func.name?.replace(/[^a-zA-Z0-9_]/g, "_") ?? "";
		if (!safeFuncName || !/^[a-zA-Z_]/.test(safeFuncName)) {
			continue; // Skip invalid function names
		}
		const params = (func.inputs ?? [])
			.map((input, i: number) => {
				const paramName = input.name ? input.name.replace(/[^a-zA-Z0-9_]/g, "_") : `arg${i}`;
				return /^[a-zA-Z_]/.test(paramName) ? paramName : `arg${i}`;
			})
			.join(", ");

		// Escape function name for safe use in string
		const safeFuncNameStr = JSON.stringify(func.name);

		code += `
async function ${safeContractName}.${safeFuncName}(${params})
  return await evm.write(
    ${safeContractName}.address,
    ${safeContractName}.abi,
    ${safeFuncNameStr},
    {${(func.inputs ?? []).map((_: unknown, i: number) => `arg${i + 1}`).join(", ")}}
  )
end
`;
	}

	if (events.length > 0) {
		// Escape event names for safe display
		const safeEventNames = events
			.map((e: ABIItem) => e.name?.replace(/[^a-zA-Z0-9_]/g, "_") ?? "")
			.filter(Boolean)
			.join(", ");
		code += `
// Events
// Note: Event listening is not yet supported in LootiScript
// Available events: ${safeEventNames}
`;
	}

	code += `
return ${safeContractName}
`;

	return code;
}
